// import { NextPageContext } from "next";
// import { playlists, playlistsItems } from "../services/videos";

// export const getServerSidePropsPlaylist = async (ctx: NextPageContext) => {
//   const { v, list, nossr } = ctx.query;

//   const listId = (list as string).match(/^RD.*/)
//     ? `RD${v}`
//     : list?.toString()! || "";

//   if (!!nossr) {
//     return {
//       props: { list: listId },
//     };
//   }
//   const data = await playlistsItems({ query: { listId } });
//   const [playlist] = await (await playlists({ query: { listId } })).items;

//   return {
//     props: {
//       list: listId,
//       data,
//       og: playlist
//         ? {
//             title: playlist.snippet.title,
//             description: playlist.snippet.description,
//             image: {
//               url: playlist.snippet.thumbnails.high.url,
//               width: playlist.snippet.thumbnails.high.width,
//               height: playlist.snippet.thumbnails.high.height,
//               alt: playlist.snippet.title,
//             },
//           }
//         : {
//             title:
//               data.playlist?.title || `Mix: ${data.items[0].snippet.title}`,
//             description: "Mix generated by d2youtube",
//             image: {
//               url: data.items[0].snippet.thumbnails.high.url,
//               width: data.items[0].snippet.thumbnails.high.width,
//               height: data.items[0].snippet.thumbnails.high.height,
//               alt: data.items[0].snippet.title,
//             },
//           },
//     },
//   };
// };
